language: java
jdk:
  - oraclejdk8
install: true
script: mvn cobertura:cobertura
after_success:
- mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
- bash <(curl -s https://codecov.io/bash) -t 97094835-4121-4248-90ec-c02d7c4c330d
